name: figma_color_cli
description: Convert Figma HEX colors into Flutter AppColor constants automatically.
version: 1.1.1
homepage: https://github.com/parthmandalia-source/figma_color_cli
repository: https://github.com/parthmandalia-source/figma_color_cli

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  figma-color: figma_color_cli
# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  http: ^1.2.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
